library(tidyverse)
library(future)
library(furrr)

make_one_investment <- function(returns_vector = c(0, 1, 3, 5, 10, 20),
                                probs_vector = c(.64, .18, .06, .07, .03, .02), investment){
  # Given a numeric initial investment, return the amount of income generated by the investment
  assertthat::assert_that(is.numeric(investment), msg = "investment must be numeric")
  assertthat::are_equal(length(returns_vector), length(probs_vector), msg = 'returns_vector and probs_vector must be the same length')
  
  sample(x = returns_vector, prob = probs_vector, size = 1, replace = TRUE) * investment
}

investment_sim <- function(investment_capital, investment_size,
                           reinvestment_perc = NULL, max_rounds = 250,
                           sim_id = 1, ...){
  # Given an initial amount of investment capital, an initial investment size and an
  # amount of profits to reinvest, return a simulated investment history
  
  
  # Amount you've made from the investments + capitalized interest after every 6 funding rounds
  total_profit <- 0
  
  # Capital you are willing to invest
  bankroll <- investment_capital
  # Total companies funded
  companies_funded = 0
  # Total rounds of funding
  funding_rounds = 0
  
  # Initialize a list; stores the results of each round
  round_results <- list()
  
  # You keep investing while your backroll is >= the minimum investment size & you haven't hit the max number of investment rounds
  while(bankroll >= investment_size & funding_rounds < max_rounds){
    
    # leftover bankroll after subtracting out cost of investment
    remainder_bankroll <- bankroll - investment_size
    
    # This is the actual simulation core. Make one investment; 
    # Returns according to make_one_investment investment returns table
    investment_revenue <- make_one_investment(investment = investment_size, ...)
    
    # Calculate profit from investments
    profit <- investment_revenue - investment_size
    
    # Iterate # of companies funded
    companies_funded <- companies_funded + 1
    
    # Iterate # of rounds into simulation 
    funding_rounds <- funding_rounds + 1
    
    
    # Every 6 rounds, capitalize the total profit made @5%. 
    if(funding_rounds %% 6 != 0){
      # If the investment generated a profit, add (1- reinvestment_perc) * profit to your total_profit
      # Add the reinvestment_perc * profit to your bankroll
      if(profit > 0){
        total_profit <- total_profit + (profit * (1 - reinvestment_perc))
        bankroll <- remainder_bankroll + investment_size + (profit * reinvestment_perc)
        # If the investment generated a loss(or was flat), add remaining bankroll + any investment revenue(which should be = investment cost)
      } else{
        bankroll <- remainder_bankroll + investment_revenue
      }
      
    } else{
      if(profit > 0){
        total_profit <- total_profit + (profit * (1 - reinvestment_perc))
        bankroll <- remainder_bankroll + investment_size + (profit * reinvestment_perc)
      } else{
        bankroll <- remainder_bankroll + investment_revenue
      }
      # Profit capitalized every 6th funding round @ 5%
      total_profit <- total_profit * 1.05
      
    }
    
    # If your total profit at least 10 times more than your initial investment capital
    # AND your current bankroll is less than the amount needed to make an investment
    # take one investment worth of money out of your profit and deposit it into your current bankroll so you
    # can continue to invest
    if(total_profit / investment_capital >= 10 & bankroll < investment_size){
      total_profit <- total_profit - investment_size
      bankroll <- bankroll + investment_size
    }
    
    # storing the results of each 'round'
    round_results[[funding_rounds]] <- tibble(
      sim_id = sim_id,
      round = funding_rounds,
      start_capital = investment_capital,
      investment_size = investment_size,
      # round level results
      revenue_for_round = investment_revenue,
      profit_for_round = profit,
      # aggregate level results
      total_realized_profit = total_profit,
      current_bankroll = bankroll, 
      total_companies_funded = companies_funded,
    )
  }
  # bind all the simulation results into one tibble
  return(purrr::list_rbind(round_results))
}


perform_sim <- function(num_sims, .starting_capital, .investment_size,
                        .reinvestment_perc, ...){
  future_map_dfr(1:num_sims, .f = function(.x, ...){
    investment_sim(investment_capital =  .starting_capital, 
                    investment_size = .investment_size,
                    reinvestment_perc = .reinvestment_perc,
                    sim_id = .x, ...)},
    ...,
    .options = furrr_options(seed = 123))
}


data_board <- pins::board_folder(path = 'data', versioned = TRUE)

plan(multisession, workers = 10)
# single_investment_small_reinvest <- perform_sim(num_sims = 100000,
#                                                 .starting_capital = 1000000,
#                                                 .investment_size = 1000000,
#                                                 .reinvestment_perc = .25)
# 
# single_investment_medium_reinvest <- perform_sim(num_sims = 100000,
#                                                 .starting_capital = 1000000,
#                                                 .investment_size = 1000000,
#                                                 .reinvestment_perc = .5)
# single_investment_large_reinvest <- perform_sim(num_sims = 100000,
#                                                 .starting_capital = 1000000,
#                                                 .investment_size = 1000000,
#                                                 .reinvestment_perc = .75)
# 
# pins::pin_write(data_board, x = single_investment_small_reinvest, name = 'single_investment_small_reinvest')
# pins::pin_write(data_board, x = single_investment_medium_reinvest, name = 'single_investment_medium_reinvest')
# pins::pin_write(data_board, x = single_investment_large_reinvest, name = 'single_investment_large_reinvest')
# 
# multiple_investment_small_reinvest <- perform_sim(num_sims = 100000,
#                                                 .starting_capital = 10000000,
#                                                 .investment_size = 1000000,
#                                                 .reinvestment_perc = .25)
# 
# multiple_investment_medium_reinvest <- perform_sim(num_sims = 100000,
#                                                  .starting_capital = 10000000,
#                                                  .investment_size = 1000000,
#                                                  .reinvestment_perc = .5)
# multiple_investment_large_reinvest <- perform_sim(num_sims = 100000,
#                                                 .starting_capital = 10000000,
#                                                 .investment_size = 1000000,
#                                                 .reinvestment_perc = .75)
# 
# pins::pin_write(data_board, x = multiple_investment_small_reinvest, name = 'multiple_investment_small_reinvest')
# pins::pin_write(data_board, x = multiple_investment_medium_reinvest, name = 'multiple_investment_medium_reinvest')
# pins::pin_write(data_board, x = multiple_investment_large_reinvest, name = 'multiple_investment_large_reinvest')
# 
# # Realistic investment table, good investors
# single_investment_realistic_investment_table_good_investor <- perform_sim(num_sims = 100000,
#                                                                           .starting_capital = 1000000,
#                                                                           .investment_size = 1000000,
#                                                                           .reinvestment_perc = .25,
#                                                                           probs_vector = c(.568, .216, .072, .084, .036, .024))
# 
# pins::pin_write(data_board, x = single_investment_realistic_investment_table_good_investor,
#                 name = 'single_investment_realistic_investment_table_good_investor')
# 
# 
# multiple_investment_realistic_investment_table_good_investor <- perform_sim(num_sims = 100000,
#                                                                           .starting_capital = 10000000,
#                                                                           .investment_size = 1000000,
#                                                                           .reinvestment_perc = .25,
#                                                                           probs_vector = c(.568, .216, .072, .084, .036, .024))
# 
# pins::pin_write(data_board, x = multiple_investment_realistic_investment_table_good_investor,
#                 name = 'multiple_investment_realistic_investment_table_good_investor')
# 
# 
# # Stingy investment table with good and regular investors, single and multiple investments
# single_investment_stingy_investment_table <- perform_sim(num_sims = 100000,
#                                                          .starting_capital = 1000000,
#                                                          .investment_size = 1000000,
#                                                          .reinvestment_perc = .25,
#                                                          returns_vector = c(0, 1, 10),
#                                                          probs_vector = c(.8, .15, .05))
# 
# pins::pin_write(data_board, x = single_investment_stingy_investment_table,
#                 name = 'single_investment_stingy_investment_table')
# 
# single_investment_stingy_investment_table_good_investor <- perform_sim(num_sims = 100000,
#                                                             .starting_capital = 1000000,
#                                                             .investment_size = 1000000,
#                                                             .reinvestment_perc = .25,
#                                                             returns_vector = c(0, 1, 10),
#                                                             probs_vector = c(.76, .18, .06))
# 
# pins::pin_write(data_board, x = single_investment_stingy_investment_table_good_investor,
#                 name = 'single_investment_stingy_investment_table_good_investor')
# 
# multiple_investment_stingy_investment_table <- perform_sim(num_sims = 100000,
#                                                            .starting_capital = 10000000,
#                                                            .investment_size = 1000000,
#                                                            .reinvestment_perc = .25,
#                                                            returns_vector = c(0, 1, 10),
#                                                            probs_vector = c(.8, .15, .05))
# 
# pins::pin_write(data_board, x = multiple_investment_stingy_investment_table,
#                 name = 'multiple_investment_stingy_investment_table')
# 
# multiple_investment_stingy_investment_good_investor <- perform_sim(num_sims = 100000,
#                                                                    .starting_capital = 10000000,
#                                                                    .investment_size = 1000000,
#                                                                    .reinvestment_perc = .25,
#                                                                    returns_vector = c(0, 1, 10),
#                                                                    probs_vector = c(.76, .18, .06))
# 
# pins::pin_write(data_board, x = multiple_investment_stingy_investment_good_investor,
#                 name = 'multiple_investment_stingy_investment_good_investor')
# 
# # Win or lose investment table, good and regular investors, single and multiple investments
# single_investment_win_or_lose <- perform_sim(num_sims = 100000,
#                                              .starting_capital = 1000000,
#                                              .investment_size = 1000000,
#                                              .reinvestment_perc = .25,
#                                              returns_vector = c(0, 50),
#                                              probs_vector = c(.99, .01))
# 
# pins::pin_write(data_board, x = single_investment_win_or_lose,
#                 name = 'single_investment_win_or_lose')
# 
# multiple_investment_win_or_lose <- perform_sim(num_sims = 100000,
#                                                .starting_capital = 10000000,
#                                                .investment_size = 1000000,
#                                                .reinvestment_perc = .25,
#                                                returns_vector = c(0, 50),
#                                                probs_vector = c(.99, .01))
# 
# pins::pin_write(data_board, x = multiple_investment_win_or_lose,
#                 name = 'multiple_investment_win_or_lose')
# 
# 
# single_investment_win_or_lose_good_investor <- perform_sim(num_sims = 100000,
#                                                            .starting_capital = 1000000,
#                                                            .investment_size = 1000000,
#                                                            .reinvestment_perc = .25,
#                                                            returns_vector = c(0, 50),
#                                                            probs_vector = c(.988, .012))
# 
# pins::pin_write(data_board, x = single_investment_win_or_lose_good_investor,
#                 name = 'single_investment_win_or_lose_good_investor')
# 
# 
# multiple_investment_win_or_lose_good_investor <- perform_sim(num_sims = 100000,
#                                                .starting_capital = 10000000,
#                                                .investment_size = 1000000,
#                                                .reinvestment_perc = .25,
#                                                returns_vector = c(0, 50),
#                                                probs_vector = c(.988, .012))
# 
# pins::pin_write(data_board, x = multiple_investment_win_or_lose_good_investor,
#                 name = 'multiple_investment_win_or_lose_good_investor')

# 
# big_multiple_investment_realistic_investment_table_good_investor <- perform_sim(num_sims = 100000,
#                                                                                 .starting_capital = 20000000,
#                                                                                 .investment_size = 1000000,
#                                                                                 .reinvestment_perc = .25,
#                                                                                 probs_vector = c(.568, .216, .072, .084, .036, .024))
# 
# big_multiple_investment_realistic_investment_table <- perform_sim(num_sims = 100000,
#                                                                   .starting_capital = 20000000,
#                                                                   .investment_size = 1000000,
#                                                                   .reinvestment_perc = .25)
# 
# 
# big_multiple_investment_stingy_investment_table_good_investor <- perform_sim(num_sims = 100000,
#                                                                .starting_capital = 20000000,
#                                                                .investment_size = 1000000,
#                                                                .reinvestment_perc = .25,
#                                                                returns_vector = c(0, 1, 10),
#                                                                probs_vector = c(.76, .18, .06))
# 
# big_multiple_investment_stingy_investment_table <- perform_sim(num_sims = 100000,
#                                                                .starting_capital = 20000000,
#                                                                .investment_size = 1000000,
#                                                                .reinvestment_perc = .25,
#                                                                returns_vector = c(0, 1, 10),
#                                                                probs_vector = c(.8, .15, .05))
# 
# big_multiple_investment_win_or_lose_good_investor <- perform_sim(num_sims = 100000,
#                                                                  .starting_capital = 20000000,
#                                                                  .investment_size = 1000000,
#                                                                  .reinvestment_perc = .25,
#                                                                  returns_vector = c(0, 50),
#                                                                  probs_vector = c(.988, .012))
# 
# big_multiple_investment_win_or_lose <- perform_sim(num_sims = 100000,
#                                                    .starting_capital = 20000000,
#                                                    .investment_size = 1000000,
#                                                    .reinvestment_perc = .25,
#                                                    returns_vector = c(0, 50),
#                                                    probs_vector = c(.99, .01))
# 
# pins::pin_write(data_board, x = big_multiple_investment_realistic_investment_table_good_investor,
#                 name = 'big_multiple_investment_realistic_investment_table_good_investor')
# 
# pins::pin_write(data_board, x = big_multiple_investment_realistic_investment_table,
#                 name = 'big_multiple_investment_realistic_investment_table')
# 
# pins::pin_write(data_board, x = big_multiple_investment_stingy_investment_table_good_investor,
#                 name = 'big_multiple_investment_stingy_investment_table_good_investor')
# 
# pins::pin_write(data_board, x = big_multiple_investment_stingy_investment_table,
#                 name = 'big_multiple_investment_stingy_investment_table')
# 
# pins::pin_write(data_board, x = big_multiple_investment_win_or_lose_good_investor,
#                 name = 'big_multiple_investment_win_or_lose_good_investor')
# 
# pins::pin_write(data_board, x = big_multiple_investment_win_or_lose,
#                 name = 'big_multiple_investment_win_or_lose')
